version: "3"
services:
  poll:
    build: ./poll
    ports:
      - "5000:80"
    networks:
      - "poll-tier"
    restart: "always"
    environment:
      - "REDIS_IP=redis"
  redis:
    image: "redis:latest"
    ports:
      - "6379"
    networks:
      - "poll-tier"
      - "back-tier"
    restart: "always"
  worker:
    build: ./worker
    networks:
      - "back-tier"
    restart: "always"
    environment:
      - "REDIS_IP=redis"
      - "DB_IP=db"
  db:
    image: "postgres:latest"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/postgresql/data
    networks:
      - "result-tier"
      - "back-tier"
    environment:
      - POSTGRES_PASSWORD=password
    restart: "always"
  result:
      build: ./result
      ports:
        - "5001:80"
      networks:
        - "result-tier"
      restart: "always"
      environment:
        - "RESULT_PORT=80"
        - "DB_IP=db"
volumes:
  db-data:
networks:
  poll-tier:
    driver: "bridge"
  result-tier:
    driver: "bridge"
  back-tier:
    driver: "bridge"