FROM jenkins:latest

RUN /usr/local/bin/install-plugins.sh cloudbees-folder configuration-as-code credentials github job-dsl script-security structs role-strategy ws-cleanup

# COPY ./sources

# env var a set