apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-postgre
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - us-east-2a    
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  local:
    path: "/mnt/data"


---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-postgre
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi